<a href="https://colab.research.google.com/github/River-Dance/Linear-Algebra/blob/main/linear_algebra_HW_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Урок 2. Линейная алгебра

In [1]:
import numpy as np

## Часть 1. Практическое задание



### __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

####Решение:

   а) $A\cdot B$ — не определено, $B\cdot A$ — не определено;
    
   б) $A\cdot B=2\times 5$ и  $5\times 3$, размер матрицы $2\times 3$

  $B\cdot A=5\times 3$ и  $2\times 5$, - не определено
    
   в) $A\cdot B$ = $8\times 3$ и $3\times 8$, размер матрицы $8\times 8$

   $B\cdot A$ = $3\times 8$ и $8\times 3$, размер матрицы $3\times 3$
    
   г) $A\cdot B$ = $4\times 4$ и $4\times 4$, размер матрицы $4\times 4$

   $B\cdot A$ = $4\times 4$ и $4\times 4$, размер матрицы $4\times 4$


###__2.__ Найти сумму и произведение матриц 
$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

#### Решение;

$A + B = \begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 0 + 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$A \cdot B = 
\begin{pmatrix}
1 \cdot 4 -2 \cdot 0 & -1 \cdot 1 -2 \cdot 5\\ 
3 \cdot 4 - 0 \cdot 0 & -1 \cdot 3 + 0 \cdot 5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11 \\ 
12 & -3
\end{pmatrix}$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A + B =\n {A+B}')
print(f'A * B =\n {np.dot(A, B)}')

A + B =
 [[ 5 -3]
 [ 3  5]]
A * B =
 [[  4 -11]
 [ 12  -3]]


###__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. 
Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

#### Решение;

$3A - 2B + 4C = 
3 \cdot \begin{pmatrix}
1 & 7 \\ 
3 & -6
\end{pmatrix}
- 2 \cdot \begin{pmatrix}
0 & 5 \\ 
2 & -1
\end{pmatrix}
+4 \cdot \begin{pmatrix}
2 & -4 \\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3 - 0 + 8 & 21 - 10 - 16\\ 
9 - 4 + 4 & -18 + 2 + 4
\end{pmatrix} = 
\begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}$

In [3]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5], [2,-1]])
C = np.array([[2,-4], [1,1]])
print(f'3*A - 2*B + 4*C = \n{3*A - 2*B + 4*C}')

3*A - 2*B + 4*C = 
[[ 11  -5]
 [  9 -12]]


###__4.__ Дана матрица 
$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

####Решение;

$A^{T}=\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}$

$A \cdot A^{T} =
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot 
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = 
\begin{pmatrix}
16+1 & 20-2 & 8+3\\ 
20-2 & 25+4 & 10-6\\ 
8+3 & 10-6 & 4+9
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$A^{T} \cdot A = 
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot 
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
\begin{pmatrix}
16 + 25 + 4 & 4 - 10 + 6 \\
4 - 10 + 6 & 1 + 4 + 9
\end {pmatrix}$


In [4]:
A = np.array([[4,1], [5,-2], [2,3]])
print(f'A*A.T = \n{np.dot(A, A.T)}')
print(f'A.T*A = \n{np.dot(A.T, A)}')

A*A.T = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]
A.T*A = 
[[45  0]
 [ 0 14]]


###__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
def composition_matrix(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        return ValueError('произведение не определено')
    result = [ [0 for j in range(len(matrix2[0]))] for i in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

Попробуем.

In [7]:
x = np.array([[5,-5], [2,0], [4,8]])
y = np.array([[5,6], [-1,4]])
print(f'Матрица Х:\n {x}')
print(f'Матрица Y:\n {y}')
print(f'Результат метода NumPy:\n {np.dot(x,y)}')
print(f'Результат метода composition_matrix: \n {composition_matrix(x,y)}')

Матрица Х:
 [[ 5 -5]
 [ 2  0]
 [ 4  8]]
Матрица Y:
 [[ 5  6]
 [-1  4]]
Результат метода NumPy:
 [[30 10]
 [10 12]
 [12 56]]
Результат метода composition_matrix: 
 [[30, 10], [10, 12], [12, 56]]


##Часть 2. Практическое задание

###__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

#### Решение:

a) $\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = \sin^2x + \cos^2x = 1$

б) $\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4(5\cdot9 - 1\cdot0) - 2(0\cdot9 - 0\cdot1) + 3(0\cdot0 - 0\cdot5) = 180$



In [8]:
a1_2 = np.array([[4,2,3], [0,5,1], [0,0,9]])
det1_2 = np.linalg.det(a1_2)
det1_2

180.0

в)  $\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 
1(5\cdot9 - 6\cdot8) -2(4\cdot9 - 6\cdot7) + 3(4\cdot8 - 5\cdot7) =
 45 - 48 - 72 + 84 + 96 - 105 = -3 - 72 + 84 - 9 =0$

In [9]:
a1_3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
det1_3 = np.linalg.det(a1_3)
det1_3

0.0



---


### __2.__ Определитель матрицы $A$ равен $4$. Найти:




   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   

#### Решение:

а) $det(A^{2}) = det(A \cdot A) = det(A)\cdot det(A) = 16$

б) $det(A^{T}) = det(A) =4$

в) $det(2A) = 2 \cdot det(A) = 8$


---



###__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

#### Решение.

Определение: 

Вырожденная матрица — квадратная матрица, определитель которой, равен нулю.

Поскольку мы можем представить вторую строку $(4, -14, 6)$ данной матрицы  через первую её строку $(4, -14, 6)$  как $(4, -14, 6)=-2\cdot (-2, 7, -3)$, т.е. две строки (столбца) матрицы линейно зависимы, а значит её определитель равен 0, т.е.

такая матрица, согласно определению, является вырожденной.

Проверка:

In [10]:
arr=np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(arr)

0.0



---
###__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$


####Решение:

а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$
Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$ 
Из первой строки вычитаем вторую и меняем строки местами:
$\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}$

Проверим:



In [11]:
arr=([[1,2,3],[1,1,1],[2,3,4]])
np.linalg.matrix_rank(arr)

2


б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ 
Третья строка является суммой первой и второй строки, отбрасываем: 
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ 
Вычитаем вторую строку из первой:
 $\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$
Удалим второй столбец, который можно выразить через первый:
$\begin{pmatrix}
0 & 0 & -1\\ 
0 & 2 & 2\\ 
2 & 5 & 6
\end{pmatrix}$
Меняем местами первую и третью строки:
$\begin{pmatrix}
2 & 5 & 6\\ 
0 & 2 & 2\\ 
0 & 0 & -1
\end{pmatrix}$
Ранг матрицы равен $3$

Проверяем:


In [12]:
arr=([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
np.linalg.matrix_rank(arr)

3